### ISSUE TITLE
pystray catches SystemExit exception when closing from tray and app never exits

### ISSUE THREAD

**Issue by AndroidWG** [AndroidWG/Discord.fm#14]
When running `close_app` from the tray icon thread, it always hangs on `sys.exit()` since pystray catches the SystemExit exception. Log output:

```
Closing app...
Closed Discord Rich Presence
An error occurred when calling message handler
Traceback (most recent call last):
  File "C:\Users\samu-\Repos\Discord.fm\venv\lib\site-packages\pystray\_win32.py", line 401, in _dispatcher
    return int(icon._message_handlers.get(
  File "C:\Users\samu-\Repos\Discord.fm\venv\lib\site-packages\pystray\_win32.py", line 213, in _on_notify
    descriptors[index - 1](self)
  File "C:\Users\samu-\Repos\Discord.fm\venv\lib\site-packages\pystray\_base.py", line 306, in inner
    callback(self)
  File "C:\Users\samu-\Repos\Discord.fm\venv\lib\site-packages\pystray\_base.py", line 431, in __call__
    return self._action(icon, self)
  File "C:\Users\samu-\Repos\Discord.fm\main.py", line 67, in close_app
    sys.exit()
SystemExit
```

**Comment by AndroidWG** [comment]
Fixed with commit 3d61bd43
