### ISSUE TITLE
Fix mysterious "OSError" when printing

### ISSUE THREAD

**Issue by AndroidWG** [AndroidWG/Discord.fm#17]
Found this log file where the app had an unexpected exception when printing the name of a setting being retrieved:
```
19:11:54.115 | DEBUG    | Finished running function "get_now_playing"
19:11:54.161 | DEBUG    | Thread result: None
19:11:54.192 | DEBUG    | Not playing anything
19:11:58.195 | DEBUG    | Thread ID: 18688
19:11:58.195 | DEBUG    | user.getRecentTracks
19:11:58.731 | DEBUG    | Finished running function "get_now_playing"
19:11:58.746 | DEBUG    | Thread result: None
19:11:58.762 | DEBUG    | Not playing anything
19:12:02.774 | DEBUG    | Thread ID: 5352
19:12:02.789 | DEBUG    | user.getRecentTracks
19:12:05.865 | DEBUG    | Finished running function "get_now_playing"
19:12:05.911 | DEBUG    | Thread result: None
19:12:05.958 | DEBUG    | Not playing anything
19:12:05.959 | DEBUG    | Running misc update
19:12:05.959 | CRITICAL | Uncaught exception
Traceback (most recent call last):
  File "C:\Users\samu-\Repos\Discord.fm\main.py", line 105, in <module>
    loop_handler.handle_update()
  File "C:\Users\samu-\Repos\Discord.fm\loop_handler.py", line 28, in handle_update
    self.sc.run()
  File "C:\Users\samu-\AppData\Local\Programs\Python\Python39\lib\sched.py", line 151, in run
    action(*argument, **kwargs)
  File "C:\Users\samu-\Repos\Discord.fm\loop_handler.py", line 63, in misc_update
    self.cooldown = local_settings.get("cooldown")
  File "C:\Users\samu-\Repos\Discord.fm\settings.py", line 78, in get
    print(f"Getting {name} setting")
OSError: [Errno 22] Invalid argument
19:12:06.003 | DEBUG    | Attempting to find Windows install...
19:12:06.003 | WARNING  | Discord.fm installation not found
19:13:58.270 | DEBUG    | Attempting to find Windows install...
19:13:58.270 | WARNING  | Discord.fm installation not found
19:14:03.771 | INFO     | Closing app...
19:14:03.792 | INFO     | Closed Discord Rich Presence
19:14:03.792 | DEBUG    | Closing 1 events...
19:14:03.793 | ERROR    | An error occurred when calling message handler
Traceback (most recent call last):
  File "C:\Users\samu-\Repos\Discord.fm\venv\lib\site-packages\pystray\_win32.py", line 401, in _dispatcher
    return int(icon._message_handlers.get(
  File "C:\Users\samu-\Repos\Discord.fm\venv\lib\site-packages\pystray\_win32.py", line 213, in _on_notify
    descriptors[index - 1](self)
  File "C:\Users\samu-\Repos\Discord.fm\venv\lib\site-packages\pystray\_base.py", line 306, in inner
    callback(self)
  File "C:\Users\samu-\Repos\Discord.fm\venv\lib\site-packages\pystray\_base.py", line 431, in __call__
    return self._action(icon, self)
  File "C:\Users\samu-\Repos\Discord.fm\main.py", line 55, in close_app
    sys.exit()
SystemExit
19:14:03.847 | INFO     | Closing app...
```

**Comment by AndroidWG** [comment]
This bug seems like a wild goose chase, I'll be closing this for now. If anyone knows what this might be or gets this error, please reopen the issue.
