### ISSUE TITLE
DiscordError when starting while Discord is open but not logged in

### ISSUE THREAD

**Issue by AndroidWG** [AndroidWG/Discord.fm#18]
Just started Windows 10 normally with Discord.fm configured to start with the system, and got this exception:

```
Traceback (most recent call last):
  File "main.py", line 101, in <module>
  File "wrappers\system_tray_icon.py", line 25, in __init__
  File "wrappers\system_tray_icon.py", line 67, in wait_for_discord
  File "wrappers\discord_rp.py", line 21, in connect
  File "pypresence\presence.py", line 45, in connect
  File "asyncio\base_events.py", line 642, in run_until_complete
  File "pypresence\baseclient.py", line 121, in handshake
pypresence.exceptions.DiscordError: Error Code: 1000 Message: User logged out
```

Probably just have to catch it and wait until Discord is fully started.

**Comment by AndroidWG** [comment]
Turns out this error is shown whenever Discord is open but not logged in and unrelated to starting with Windows (wow, maybe read the error properly next time?)
