### ISSUE TITLE
"pylast.WSError: Operation failed" happened randomly

### ISSUE THREAD

**Issue by AndroidWG** [AndroidWG/Discord.fm#19]
Fix this error that happened randomly while using the computer normally:

```
Traceback (most recent call last):
  File "main.py", line 20, in <module>
  File "app_manager.py", line 79, in start
  File "loop_handler.py", line 30, in handle_update
  File "sched.py", line 151, in run
  File "loop_handler.py", line 41, in _lastfm_update
  File "wrappers\last_fm_user.py", line 29, in now_playing
  File "util\request_handler.py", line 103, in attempt_request
  File "util\request_handler.py", line 125, in _wrapper
  File "pylast\__init__.py", line 2327, in get_now_playing
  File "pylast\__init__.py", line 1142, in _request
  File "pylast\__init__.py", line 978, in execute
  File "pylast\__init__.py", line 967, in _download_response
  File "pylast\__init__.py", line 997, in _check_response_for_errors
pylast.WSError: Operation failed - Most likely the backend service failed. Please try again.
```

**Comment by AndroidWG** [comment]
Fixed with 3e67f791d286e2ac9b7cf08260183ec6b1721c79
