### ISSUE TITLE
WSError: User not found

### ISSUE THREAD

**Issue by androidWG** [androidWG/Discord.fm#21]
Randomly received this error while running on the background. Couldn't figure out why it happens - may be an internal Last.fm error that PyLast is interpreting incorrectly? The username in my settings is correct.

```
Traceback (most recent call last):
  File "main.py", line 25, in <module>
  File "app_manager.py", line 74, in start
  File "loop_handler.py", line 30, in handle_update
  File "sched.py", line 151, in run
  File "loop_handler.py", line 41, in _lastfm_update
  File "wrappers\last_fm_user.py", line 29, in now_playing
  File "util\request_handler.py", line 104, in attempt_request
  File "util\request_handler.py", line 126, in _wrapper
  File "pylast\__init__.py", line 2327, in get_now_playing
  File "pylast\__init__.py", line 1142, in _request
  File "pylast\__init__.py", line 978, in execute
  File "pylast\__init__.py", line 967, in _download_response
  File "pylast\__init__.py", line 997, in _check_response_for_errors
pylast.WSError: User not found
```

**Comment by androidWG** [comment]
This bug is very mysterious and I did not collect enough data when it happened. This is closed until we get more data on it.
