### ISSUE TITLE
Using "Enable Rich Presence" causes the application to freeze

### ISSUE THREAD

**Issue by philfiru** [androidWG/Discord.fm#28]
If you turn off "Enable Rich Presence" and then turn it back on, the application freezes. The only way to get it running again is to stop the service in Task Manager. There is no indication of the crash in the logs, but the application window does not respond anymore.

Running on Windows 10 Pro 21H1.

![image](https://user-images.githubusercontent.com/53810001/197699766-d613c541-4db0-4e12-a6e8-d8ac12bf49c6.png)

[_discord.fm_2022-10-25_06-30-53.log](https://github.com/androidWG/Discord.fm/files/9857683/_discord.fm_2022-10-25_06-30-53.log)

**Comment by adeleine1412** [comment]
I've gone ahead and setup the dev environment, this way its harder for the application to freeze, but it happens eventually, here's the only output I could catch.

This also seems to happen when you restart Discord and then try to turn "Enable Rich Presence" on and off.

```bash
adeleine@DESKTOP-0D3V944 MINGW64 ~/Desktop/Discord.fm (main)
$ Application started
Folder "C:\Users\adeleine\AppData\Roaming\Discord.fm" already exists
Folder "C:\Users\adeleine\AppData\Local\Discord.fm" already exists
Getting username setting
Getting username setting
Getting cooldown setting
Getting debug setting
Deleting old logs
Getting max_logs setting
Deleting file C:\Users\adeleine\AppData\Local\Discord.fm\_discord.fm_2022-10-25_12-40-03.log
Getting debug setting
Getting debug setting
Logging setup finished
Getting debug setting
[INFO] (main.py:19)  -------- Discord.fm version 0.8.0  --------
[INFO] (main.py:23) Current working path: "C:\Users\adeleine\Desktop\Discord.fm\src"
[INFO] (app_manager.py:158) Attempting to connect to Discord
[INFO] (discord_rp.py:26) Connected to Discord
[INFO] (app_manager.py:167) Successfully connected to Discord
[WARNING] (app_manager.py:52) Running in non-frozen mode
Getting auto_update setting
Getting pre_releases setting
[INFO] (discord_rp.py:43) Now playing: Baum
Getting cooldown setting
Getting username setting
[INFO] (discord_rp.py:30) Cleared Discord status
[INFO] (system_tray_icon.py:78) Changed state to False
[INFO] (discord_rp.py:26) Connected to Discord
[INFO] (system_tray_icon.py:78) Changed state to True
[INFO] (discord_rp.py:30) Cleared Discord status
[INFO] (system_tray_icon.py:78) Changed state to False
[INFO] (discord_rp.py:26) Connected to Discord
[INFO] (system_tray_icon.py:78) Changed state to True
[INFO] (discord_rp.py:30) Cleared Discord status
[INFO] (system_tray_icon.py:78) Changed state to False
[INFO] (discord_rp.py:26) Connected to Discord
[INFO] (system_tray_icon.py:78) Changed state to True
Exception ignored in: <function _ProactorBasePipeTransport.__del__ at 0x000002001DBE7D90>
Traceback (most recent call last):
  File "C:\Python310\lib\asyncio\proactor_events.py", line 115, in __del__
    _warn(f"unclosed transport {self!r}", ResourceWarning, source=self)
  File "C:\Python310\lib\asyncio\proactor_events.py", line 79, in __repr__
    info.append(f'fd={self._sock.fileno()}')
  File "C:\Python310\lib\asyncio\windows_utils.py", line 102, in fileno
    raise ValueError("I/O operation on closed pipe")
ValueError: I/O operation on closed pipe
$ Getting cooldown setting
Getting username setting
[INFO] (discord_rp.py:30) Cleared Discord status
[INFO] (system_tray_icon.py:78) Changed state to False
[INFO] (discord_rp.py:26) Connected to Discord
[INFO] (system_tray_icon.py:78) Changed state to True
Getting username setting
Getting cooldown setting
Getting start_with_system setting
Getting auto_update setting
Getting pre_releases setting
Getting debug setting
Running _check_username
debounce is none
Getting username setting
Setting value of "cooldown" setting to "5"
Setting value of "cooldown" setting to "4"
Setting value of "username" setting to "adeleine1412"
Getting cooldown setting
Getting username setting
[INFO] (discord_rp.py:26) Connected to Discord
[INFO] (system_tray_icon.py:78) Changed state to True
[INFO] (discord_rp.py:30) Cleared Discord status
[INFO] (system_tray_icon.py:78) Changed state to False
[INFO] (discord_rp.py:26) Connected to Discord
[INFO] (system_tray_icon.py:78) Changed state to True
```

**Comment by androidWG** [comment]
I tried disabling and enabling Rich Presence and it did work, however only re-appeared on Discord when the song changed. The UI acts really weird though after changing it from the tray icon.

Overall, it took a lot of enabling/disabling it in sequence to get it to freeze. This needs quite a bit more probing. I'm currently making unit and starting on integration tests to catch exactly this type of problem.

Makes no sense why it seems to freeze only sometimes 🤔

**Comment by androidWG** [comment]
Small update on this issue:
Seems like Discord simply disregards the Rich Presence if you disable it and enable again but push the same presence as the last. I'll try circumventing his by pushing a simple fake presence before.

**Comment by androidWG** [comment]
I've made some changes on how toggling Rich Presence is handled to make it more reliable and make sure the current playing song is always shown when enabling it. This issue seems to be solved. If more testing shows it returning, I'll open this issue or create a new one.
