### ISSUE TITLE
[Bug] No module named 'pywintypes' on startup for GitHub Actions Windows builds

### ISSUE THREAD

**Issue by androidWG** [androidWG/Discord.fm#41]
I got this notification after just starting the app on Windows. Probably hidden import, but never had this issue before. Seems weird it'd start to do that only now.
```
Traceback (most recent call last):
  File "main.py", line 7, in <module>
  File "PyInstaller\loader\pyimod02_importers.py", line 419, in exec_module
  File "app_manager.py", line 16, in <module>
  File "PyInstaller\loader\pyimod02_importers.py", line 419, in exec_module
  File "ui\__init__.py", line 21, in <module>
  File "ui\__init__.py", line 25, in SettingsWindow
  File "util\install\__init__.py", line 29, in get_install
  File "importlib\__init__.py", line 126, in import_module
  File "PyInstaller\loader\pyimod02_importers.py", line 419, in exec_module
  File "util\install\windows.py", line 7, in <module>
ModuleNotFoundError: No module named 'pywintypes'
```

**Comment by androidWG** [comment]
Only happens on builds built with GitHub Actions. Most likely scenario is the files are missing from the "lib" directory in Python, like from this answer: https://stackoverflow.com/a/60252954/8286014

**Comment by androidWG** [comment]
Solved as of last PR #50
