### ISSUE TITLE
[Bug] Won't start, directory not found?

### ISSUE THREAD

**Issue by AngelGonePro** [androidWG/Discord.fm#44]
__Logs:__
angel@linux-B550:~$ git clone https://github.com/androidWG/Discord.fm
cd Discord.fm
python setup.py setup
Cloning into 'Discord.fm'...
remote: Enumerating objects: 3546, done.
remote: Counting objects: 100% (1072/1072), done.
remote: Compressing objects: 100% (387/387), done.
remote: Total 3546 (delta 680), reused 990 (delta 650), pack-reused 2474
Receiving objects: 100% (3546/3546), 21.55 MiB | 24.85 MiB/s, done.
Resolving deltas: 100% (2231/2231), done.

Getting venv...
Running simple command "pipenv --venv"...

Traceback (most recent call last):
  File "/home/angel/Discord.fm/setup.py", line 202, in <module>
    check_venv(args.force, args.no_venv)
  File "/home/angel/Discord.fm/setup.py", line 73, in check_venv
    env_name = _run_simple("pipenv --venv")
  File "/home/angel/Discord.fm/setup.py", line 50, in _run_simple
    process = subprocess.Popen(
  File "/usr/lib/python3.10/subprocess.py", line 971, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/usr/lib/python3.10/subprocess.py", line 1863, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'pipenv'

__OS Info:__

ngel@linux-B550:~$ neofetch
             ...-:::::-...                 angel@linux-B550 
          .-MMMMMMMMMMMMMMM-.              ---------------- 
      .-MMMM`..-:::::::-..`MMMM-.          OS: Linux Mint 21.3 x86_64 
    .:MMMM.:MMMMMMMMMMMMMMM:.MMMM:.        Host: B550 
   -MMM-M---MMMMMMMMMMMMMMMMMMM.MMM-       Kernel: 6.5.0-1027-oem 
 `:MMM:MM`  :MMMM:....::-...-MMMM:MMM:`    Uptime: 2 hours, 7 mins 
 :MMM:MMM`  :MM:`  ``    ``  `:MMM:MMM:    Packages: 3042 (dpkg), 13 (flatpak) 
.MMM.MMMM`  :MM.  -MM.  .MM-  `MMMM.MMM.   Shell: bash 5.1.16 
:MMM:MMMM`  :MM.  -MM-  .MM:  `MMMM-MMM:   Resolution: 3840x2160 
:MMM:MMMM`  :MM.  -MM-  .MM:  `MMMM:MMM:   DE: Xfce 4.18 
:MMM:MMMM`  :MM.  -MM-  .MM:  `MMMM-MMM:   WM: Xfwm4 
.MMM.MMMM`  :MM:--:MM:--:MM:  `MMMM.MMM.   WM Theme: Mint-Y-Aqua 
 :MMM:MMM-  `-MMMMMMMMMMMM-`  -MMM-MMM:    Theme: Adwaita-dark [GTK2/3] 
  :MMM:MMM:`                `:MMM:MMM:     Icons: Mint-Y-Sand [GTK2/3] 
   .MMM.MMMM:--------------:MMMM.MMM.      Terminal: xfce4-terminal 
     '-MMMM.-MMMMMMMMMMMMMMM-.MMMM-'       Terminal Font: Monospace 12 
       '.-MMMM``--:::::--``MMMM-.'         CPU: AMD Ryzen 7 5700G with Radeon G 
            '-MMMMMMMMMMMMM-'              GPU: AMD ATI 08:00.0 Cezanne 
               ``-:::::-``                 GPU: NVIDIA GeForce RTX 3060 Lite Ha 
                                           Memory: 4388MiB / 63674MiB 

                                                                   
                                                                   

angel@linux-B550:~$

**Comment by AngelGonePro** [comment]
__Update:__

angel@linux-B550:~/Discord.fm$ python setup.py setup

Getting venv...
Running simple command "pipenv --venv"...

No virtualenv has been created for this project/home/angel/Discord.fm yet!
Aborted!
Running pipenv...

Running simple command "pipenv --python=3.11 install --dev"...

Warning: Python 3.11 was not found on your system...
Neither 'pyenv' nor 'asdf' could be found to install Python.
You can specify specific versions of Python with:
$ pipenv --python path/to/python
Running simple command "pipenv --venv"...

No virtualenv has been created for this project/home/angel/Discord.fm yet!
Aborted!
Running simple command "pipenv --py"...

No virtualenv has been created for this project /home/angel/Discord.fm  yet!
Aborted!
Python path: 
Env path: 
Pip path: ['', '-m', 'pip', 'install']

Setup completed
angel@linux-B550:~/Discord.fm$

**Comment by AngelGonePro** [comment]
__Another Update:__

angel@linux-B550:~/Discord.fm$ python setup.py setup

Getting venv...
Running simple command "pipenv --venv"...

No virtualenv has been created for this project/home/angel/Discord.fm yet!
Aborted!
Running pipenv...

Running simple command "pipenv --python=3.11 install --dev"...

Creating a virtualenv for this project...
Pipfile: /home/angel/Discord.fm/Pipfile
Using /usr/bin/python3.11 (3.11.9) to create virtualenv...
created virtual environment CPython3.11.9.final.0-64 in 232ms
  creator CPython3Posix(dest=/home/angel/.local/share/virtualenvs/Discord.fm-stLX6RFd, clear=False, no_vcs_ignore=False, global=False)
  seeder FromAppData(download=False, pip=bundle, setuptools=bundle, wheel=bundle, via=copy, app_data_dir=/home/angel/.local/share/virtualenv)
    added seed packages: pip==24.1, setuptools==70.1.0, wheel==0.43.0
  activators BashActivator,CShellActivator,FishActivator,NushellActivator,PowerShellActivator,PythonActivator

✔ Successfully created virtual environment!
Virtualenv location: /home/angel/.local/share/virtualenvs/Discord.fm-stLX6RFd
Pipfile.lock not found, creating...
Locking [packages] dependencies...
Building requirements...
Resolving dependencies...
False
✘ Locking Failed!
Could not find a matching version of pywin32>=306; sys_platform == "windows" for your environment, its dependencies will be skipped.
Could not find a matching version of aquaui>=0.0.1.post2; sys_platform == "darwin" for your environment, its dependencies will be skipped.
Could not find a matching version of pyobjc>=10.0; sys_platform == "darwin" for your environment, its dependencies will be skipped.
ERROR:pip.subprocessor:pip subprocess to install build dependencies exited with 1
[ResolutionFailure]:   File "/home/angel/.local/lib/python3.10/site-packages/pipenv/resolver.py", line 645, in _main
[ResolutionFailure]:       resolve_packages(
[ResolutionFailure]:   File "/home/angel/.local/lib/python3.10/site-packages/pipenv/resolver.py", line 612, in resolve_packages
[ResolutionFailure]:       results, resolver = resolve(
[ResolutionFailure]:       ^^^^^^^^
[ResolutionFailure]:   File "/home/angel/.local/lib/python3.10/site-packages/pipenv/resolver.py", line 592, in resolve
[ResolutionFailure]:       return resolve_deps(
[ResolutionFailure]:       ^^^^^^^^^^^^^
[ResolutionFailure]:   File "/home/angel/.local/lib/python3.10/site-packages/pipenv/utils/resolver.py", line 932, in resolve_deps
[ResolutionFailure]:       results, hashes, internal_resolver = actually_resolve_deps(
[ResolutionFailure]:       ^^^^^^^^^^^^^^^^^^^^^^
[ResolutionFailure]:   File "/home/angel/.local/lib/python3.10/site-packages/pipenv/utils/resolver.py", line 700, in actually_resolve_deps
[ResolutionFailure]:       resolver.resolve()
[ResolutionFailure]:   File "/home/angel/.local/lib/python3.10/site-packages/pipenv/utils/resolver.py", line 457, in resolve
[ResolutionFailure]:       raise ResolutionFailure(message=str(e))
[pipenv.exceptions.ResolutionFailure]: Warning: Your dependencies could not be resolved. You likely have a mismatch in your sub-dependencies.
  You can use $ pipenv run pip install <requirement_name> to bypass this mechanism, then run $ pipenv graph to inspect the versions actually installed in the virtualenv.
  Hint: try $ pipenv lock --pre if it is a pre-release dependency.
ERROR: pip subprocess to install build dependencies exited with 1

Traceback (most recent call last):
  File "/usr/bin/pipenv", line 33, in <module>
    sys.exit(load_entry_point('pipenv==11.9.0', 'console_scripts', 'pipenv')())
  File "/home/angel/.local/lib/python3.10/site-packages/pipenv/vendor/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
  File "/home/angel/.local/lib/python3.10/site-packages/pipenv/cli/options.py", line 58, in main
    return super().main(*args, **kwargs, windows_expand_args=False)
  File "/home/angel/.local/lib/python3.10/site-packages/pipenv/vendor/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
  File "/home/angel/.local/lib/python3.10/site-packages/pipenv/vendor/click/core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/angel/.local/lib/python3.10/site-packages/pipenv/vendor/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/angel/.local/lib/python3.10/site-packages/pipenv/vendor/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
  File "/home/angel/.local/lib/python3.10/site-packages/pipenv/vendor/click/decorators.py", line 92, in new_func
    return ctx.invoke(f, obj, *args, **kwargs)
  File "/home/angel/.local/lib/python3.10/site-packages/pipenv/vendor/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
  File "/home/angel/.local/lib/python3.10/site-packages/pipenv/cli/command.py", line 209, in install
    do_install(
  File "/home/angel/.local/lib/python3.10/site-packages/pipenv/routines/install.py", line 93, in do_install
    do_init(
  File "/home/angel/.local/lib/python3.10/site-packages/pipenv/routines/install.py", line 653, in do_init
    do_lock(
  File "/home/angel/.local/lib/python3.10/site-packages/pipenv/routines/lock.py", line 66, in do_lock
    venv_resolve_deps(
  File "/home/angel/.local/lib/python3.10/site-packages/pipenv/utils/resolver.py", line 873, in venv_resolve_deps
    c = resolve(cmd, st, project=project)
  File "/home/angel/.local/lib/python3.10/site-packages/pipenv/utils/resolver.py", line 737, in resolve
    raise RuntimeError("Failed to lock Pipfile.lock!")
RuntimeError: Failed to lock Pipfile.lock!
Running simple command "pipenv --venv"...

/home/angel/.local/share/virtualenvs/Discord.fm-stLX6RFd
Running simple command "pipenv --py"...

/home/angel/.local/share/virtualenvs/Discord.fm-stLX6RFd/bin/python
Python path: /home/angel/.local/share/virtualenvs/Discord.fm-stLX6RFd/bin/python
Env path: /home/angel/.local/share/virtualenvs/Discord.fm-stLX6RFd
Pip path: ['/home/angel/.local/share/virtualenvs/Discord.fm-stLX6RFd/bin/python', '-m', 'pip', 'install']

Setup completed
angel@linux-B550:~/Discord.fm$

**Comment by androidWG** [comment]
I've completely changed the setup script now using `uv` instead of pipenv. You can try updating the code with `git pull`, running `pip install packaging psutil` to install required packages for the setup script and then running `python setup.py run`.

Just to note that running the app unfrozen (aka just from `python setup.py run`) as an end user isn't really the way it's supposed to be run for daily use, and won't have auto updates or easily start with the system.
